markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 闭门造轮子
host: mytharcher.github.io
desc: 造轮子工程师的代码笔记

custom:
    category:
        thinking: 闭门思考
        experience: 问题即经验
        discovery: 日新月异
        criticism: 非专业吐槽
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  experience
        title: 问题即经验

      - name:  discovery
        title: 日新月异

      - name:  criticism
        title: 非专业吐槽

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: mytharcher
        email: mytharcher@gmail.com
        disqus: tech-justlog-me                     # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: mytharcher                          # GitHub账号
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
